# Generated by Django 3.0.4 on 2020-03-25 08:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookinventery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='request_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 25, 8, 15, 49, 657688, tzinfo=utc)),
        ),
    ]
