# Generated by Django 3.0.4 on 2020-03-26 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookinventery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookinventery.BookDetail')),
            ],
        ),
        migrations.CreateModel(
            name='WaitingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('Waiting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookinventery.Waiting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='waiting',
            name='user',
            field=models.ManyToManyField(through='bookinventery.WaitingTime', to=settings.AUTH_USER_MODEL),
        ),
    ]
