# Generated by Django 3.0.4 on 2020-03-24 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookinventery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdetail',
            old_name='auther',
            new_name='author',
        ),
    ]
