# Generated by Django 3.0.4 on 2020-03-26 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookinventery', '0002_auto_20200326_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitingtime',
            old_name='Waiting',
            new_name='waiting',
        ),
    ]
