# Generated by Django 3.0.4 on 2020-03-25 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookinventery', '0002_auto_20200325_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
