# Generated by Django 3.0.4 on 2020-03-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinventery', '0003_auto_20200324_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
