# Generated by Django 3.0.4 on 2020-03-26 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookinventery', '0003_auto_20200326_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='issue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
